name: Deploy - AWS

on:
  workflow_dispatch:

jobs:
  deploy-aws:
    environment:
      name: "Production"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code
        run: cd invoice2-team && npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Create environments directory and file
        run: |
          mkdir environments
          echo "export const environment = { ENV_FILE: '${{ secrets.ENV_FILE }}' };" > environments/environment.ts

      - name: Build app
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: npx nx run apps/invoice2:build

      - name: Configure AWS credentials for S3
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS
        run: cd dist/apps/invoice2 && aws s3 sync dist s3://invoices2-aws-bucket-001
