name: Deploy - AWS

on:
  workflow_dispatch:

jobs:
  deploy-aws:
    environment:
      name: "Production"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: |
          cd invoice2-team
          npm ci

      - name: Install nx globally
        run: npm install -g nx

      - name: Install i18n
        run: npm install i18n-iso-countries

      - name: Lint code
        run: |
          cd invoice2-team/apps/invoice2
          npm run lint

      - name: Debug ENV_FILE
        run: echo "${{ secrets.ENV_FILE }}"
        shell: bash

      - name: Create environments directory and file
        run: |
          mkdir -p invoice2-team/environments
          cd invoice2-team/environments
          echo "my env value is: ${{ secrets.ENV_FILE }}"
          echo "${{ secrets.ENV_FILE }}" > environment.development.ts
          echo "Env file is:"
          cat environment.development.ts
        shell: bash

      - name: Build app
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          cd invoice2-team
          nx run user-panel:build --configuration=production

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Configure AWS credentials for S3
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS
        run: |
          cd invoice2-team/dist/user-panel
          aws s3 sync . s3://invoices2-aws-bucket-001
